# ============================================================
# ARREST GAME
# File : core/sound.sk
# Version : v0.0.04
#
# サウンド共通処理
#
# ・逮捕
# ・保釈
# ・時間切れ釈放
#
# 罪状ごとの個別設定は行わず、共通処理として管理する。
# ============================================================


# ============================================================
# 逮捕
# ============================================================

function arrest_sound_arrest(p: player):
    play sound "block.iron_door.close" with volume 1 and pitch 0.8 to {_p}


# ============================================================
# 保釈
# ============================================================

function arrest_sound_bail(p: player):
    play sound "entity.player.levelup" with volume 0.7 and pitch 1.2 to {_p}


# ============================================================
# 時間切れ釈放
# ============================================================

function arrest_sound_release(p: player):
    play sound "block.note_block.pling" with volume 0.8 and pitch 1.5 to {_p}
