every 5 ticks:

    loop all players:

        set {_p} to loop-player

        if gamemode of {_p} is not survival:
            continue

        if world of {_p} is not {arrest::world}:
            continue

        set {_x} to floor(x-coordinate of {_p})
        set {_y} to floor(y-coordinate of {_p})
        set {_z} to floor(z-coordinate of {_p})

        send action bar "X:%{_x}% Y:%{_y}% Z:%{_z}% / 足元:%block at location({_x}, {_y}, {_z}, world of {_p})%" to {_p}
